<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="14" hostname="TR-JDGMXY2" failures="3" tests="3" name="com.trgr.quality.maf.tests.LoginTest" time="1005.950" errors="0" timestamp="08 Feb 2021 20:28:34 GMT" skipped="0">
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="loginWithValidAndInvalidCredentials" time="523.416">
    <failure message="The following asserts failed:
	MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid username expected [true] but found [false],
	MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid password expected [true] but found [false],
	Exception in Test expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid username expected [true] but found [false],
	MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid password expected [true] but found [false],
	Exception in Test expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.trgr.quality.maf.tests.LoginTest.loginWithValidAndInvalidCredentials(LoginTest.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
    </failure>
  </testcase> <!-- loginWithValidAndInvalidCredentials -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="loginUsingSaveUserNameAndPwd" time="241.841">
    <failure message="The following asserts failed:
	Exception in Test expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Exception in Test expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.trgr.quality.maf.tests.LoginTest.loginUsingSaveUserNameAndPwd(LoginTest.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
    </failure>
  </testcase> <!-- loginUsingSaveUserNameAndPwd -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="loginUsingSaveUserName" time="240.693">
    <failure message="The following asserts failed:
	Exception in Test expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Exception in Test expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.trgr.quality.maf.tests.LoginTest.loginUsingSaveUserName(LoginTest.java:432)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
    </failure>
  </testcase> <!-- loginUsingSaveUserName -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="CustomerServicePortlet">
    <skipped/>
  </testcase> <!-- CustomerServicePortlet -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="onepassSignInlinks">
    <skipped/>
  </testcase> <!-- onepassSignInlinks -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="FrequentQuestionsLink">
    <skipped/>
  </testcase> <!-- FrequentQuestionsLink -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="loginWithClientID">
    <skipped/>
  </testcase> <!-- loginWithClientID -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="GoToHomeFromServicesPage">
    <skipped/>
  </testcase> <!-- GoToHomeFromServicesPage -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="onepasspageprofilelinks">
    <skipped/>
  </testcase> <!-- onepasspageprofilelinks -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="InteractiveDemoLink">
    <skipped/>
  </testcase> <!-- InteractiveDemoLink -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="LoginwithSaveUnamePwdUnchecked">
    <skipped/>
  </testcase> <!-- LoginwithSaveUnamePwdUnchecked -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="ForgotUsernamePasswordLinks">
    <skipped/>
  </testcase> <!-- ForgotUsernamePasswordLinks -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="ForgotPasswordLinks">
    <skipped/>
  </testcase> <!-- ForgotPasswordLinks -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="LoginScreenDesignForAnyUser">
    <skipped/>
  </testcase> <!-- LoginScreenDesignForAnyUser -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="LoginScreenDesignForFirstTimeUser">
    <skipped/>
  </testcase> <!-- LoginScreenDesignForFirstTimeUser -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="LoginBranding">
    <skipped/>
  </testcase> <!-- LoginBranding -->
  <testcase classname="com.trgr.quality.maf.tests.LoginTest" name="KnowtheServiceLink">
    <skipped/>
  </testcase> <!-- KnowtheServiceLink -->
</testsuite> <!-- com.trgr.quality.maf.tests.LoginTest -->
